# Site settings
title: Vikram Somu
email: vs19@gatech.edu
description: "This is my portfolio."
baseurl: ""
url: ""
host: localhost
port: 8080

# Build settings
paginate: 10
# paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighting: true