# Site settings
title: Vikram Somu
email: vs19@gatech.edu
description: "Welcome to my personal website."
github_user: vi-s
baseurl: ""
url: ""
host: localhost
port: 8080

# Build settings
paginate: 10
# paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighting: true